### ISSUE TITLE
Could not find required constructor arguments for PaypalServerSdkLib\\Models\\NetworkTransactionReference: id

### ISSUE THREAD

**Issue by james-ingold** [paypal/PayPal-PHP-Server-SDK#10]
Just started getting this error in the sandbox when calling ordersCapture. I've been testing error handling so not sure if I've made too many calls or something. Order is created and then the error happens on capture. This was working previously. 

$captureBody = {"id":"0SV24052CE043231L"}

$apiResponse = $this->client->getOrdersController()->ordersCapture($captureBody);

```
[2024-10-30 15:18:49] local.ERROR: Could not find required constructor arguments for PaypalServerSdkLib\Models\NetworkTransactionReference: id {"userId":"43d41861-7d07-4676-82cb-6833e5aef5f1","exception":"[object] (apimatic\\js10:18:49 [42/1581]
erException(code: 0): Could not find required constructor arguments for PaypalServerSdkLib\\Models\\NetworkTransactionReference: id at localhost/vendor/apimatic/jsonmapper/src/JsonMapperException.php:169)
[stacktrace]
#0 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(1825): apimatic\\jsonmapper\\JsonMapperException::fewerArgumentsException('PaypalServerSdk...', Array)
#1 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(1189): apimatic\\jsonmapper\\JsonMapper->createInstance('PaypalServerSdk...', Object(stdClass), false)
#2 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(529): apimatic\\jsonmapper\\JsonMapper->mapClass(Object(stdClass), '\\\\PaypalServerSd...', false)
#3 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(304): apimatic\\jsonmapper\\JsonMapper->getMappedValue(Object(stdClass), '\\\\PaypalServerSd...', NULL, NULL, 'PaypalServerSdk...', 'PaypalServerSdk...',
 false)
#4 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(1428): apimatic\\jsonmapper\\JsonMapper->map(Object(stdClass), Object(PaypalServerSdkLib\\Models\\Capture), false)
#5 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(510): apimatic\\jsonmapper\\JsonMapper->mapArray(Array, Array, '\\\\PaypalServerSd...', 1, false)                                                        #6 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(304): apimatic\\jsonmapper\\JsonMapper->getMappedValue(Array, 'Capture[]', NULL, NULL, 'PaypalServerSdk...', 'PaypalServerSdk...', false)
#7 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(1199): apimatic\\jsonmapper\\JsonMapper->map(Object(stdClass), Object(PaypalServerSdkLib\\Models\\PaymentCollection), false)
#8 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(529): apimatic\\jsonmapper\\JsonMapper->mapClass(Object(stdClass), '\\\\PaypalServerSd...', false)
#9 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(304): apimatic\\jsonmapper\\JsonMapper->getMappedValue(Object(stdClass), '\\\\PaypalServerSd...', NULL, NULL, 'PaypalServerSdk...', 'PaypalServerSdk...', false)
#10 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(1428): apimatic\\jsonmapper\\JsonMapper->map(Object(stdClass), Object(PaypalServerSdkLib\\Models\\PurchaseUnit), false)
#11 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(510): apimatic\\jsonmapper\\JsonMapper->mapArray(Array, Array, '\\\\PaypalServerSd...', 1, false)
#12 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(304): apimatic\\jsonmapper\\JsonMapper->getMappedValue(Array, 'PurchaseUnit[]', NULL, NULL, 'PaypalServerSdk...', 'PaypalServerSdk...', false)
#13 localhost/vendor/apimatic/jsonmapper/src/JsonMapper.php(1199): apimatic\\jsonmapper\\JsonMapper->map(Object(stdClass), Object(PaypalServerSdkLib\\Models\\Order), false)                                        #14 localhost/vendor/apimatic/core/src/Utils/JsonHelper.php(71): apimatic\\jsonmapper\\JsonMapper->mapClass(Object(stdClass), 'PaypalServerSdk...')
#15 localhost/vendor/apimatic/core/src/Response/Types/ResponseType.php(65): Core\\Utils\\JsonHelper->mapClass(Object(stdClass), 'PaypalServerSdk...', 0)                                                            #16 localhost/vendor/apimatic/core/src/Response/ResponseHandler.php(178): Core\\Response\\Types\\ResponseType->getFrom(Object(Core\\Response\\Context))
#17 localhost/vendor/apimatic/core/src/ApiCall.php(51): Core\\Response\\ResponseHandler->getResult(Object(Core\\Response\\Context))
#18 localhost/vendor/paypal/paypal-server-sdk/src/Controllers/BaseController.php(40): Core\\ApiCall->execute()
#19 localhost/vendor/paypal/paypal-server-sdk/src/Controllers/OrdersController.php(345): PaypalServerSdkLib\\Controllers\\BaseController->execute(Object(Core\\Request\\RequestBuilder), Object(Core\\Response\\Resp
onseHandler))
```

**Comment by james-ingold** [comment]
Seem to be randomly getting this issue in production fyi. The order id is populated. 

{"id":"_theOrderId_"}

$this->client->getOrdersController()->ordersCapture($captureBody);

apimatic\jsonmapper\JsonMapperException: Could not find required constructor arguments for PaypalServerSdkLib\Models\NetworkTransactionReference: id

**Comment by james-ingold** [comment]
Switching back to old payment flow until this is resolved

**Comment by alisacorporation** [comment]
$captureBody = {"id":"0SV24052CE043231L"} is this legit for php?

$captureBody = ['id' => '0SV24052CE043231L'];

**Comment by james-ingold** [comment]
yes, most of our transactions are going through. This issue occurs occasionally and from the call stack is from parsing the response in the Paypal PHP Server.

**Comment by james-ingold** [comment]
@DPoplin Hey do you have any insight into this issue? I also received a support response from Paypal Technical Support that this library is deprecated which is hopefully not the case.

**Comment by PrestonPHX** [comment]
This library is not deprecated; it is new and in beta, some kinks left to work out apparently...

That confusion must arise because a much older repository, called "PayPal-PHP-SDK" (no "server-") was long ago deprecated

**Comment by LeonarthusMectus** [comment]
Hello all.  Apologies for being late to the discussion.

@james-ingold I can confirm that @PrestonPHX is correct, this SDK is part of six (6) new SDKs we are building to replace older deprecated SDKs.  There may be some folks on our support teams who aren't aware of this.  In any case, I and my team are very much working on them to correct issues and add additional features.

To the point, would it be possible for you to grab a debug ID from a failed request as well as a non-failed request for me?  These should be available in the response headers or possibly logged by the SDK depending on your logging config.  With those I can take a look and try to compare what's going on here.

**Comment by james-ingold** [comment]
Thanks @LeonarthusMectus for checking this out. Just to clarify these are all successful, non-failed responses in paypal, (200, 201 response codes) but seem to be erroring in the SDK when parsing the response:

Example request that threw this error: DEBUG ID: 6f4811777118b (capture request)
Request that did not throw this error: DEBUG ID: 1c9d2861bc074 (capture request)

**Comment by james-ingold** [comment]
3 more examples from today: @LeonarthusMectus 

DEBUG ID: 030f6676c8f78
DEBUG ID: 6375849bf2e17
DEBUG ID:

**Comment by james-ingold** [comment]
Not sure if it helps but these _seem_ to be debit cards when this occurs, but that might just be a coincidence

**Comment by LeonarthusMectus** [comment]
Perfect!  Thanks for those.  It definitely looks like all these instances are all Debit cards, and are missing the `id` property of the network transaction reference object in the capture response, which from what I understand should always be present.  

I'm following up with some colleagues on our API teams to try and understand the relationship between Debit networks & the network transaction reference to work out if there's a case where the ID would not be present, or if it's mistakenly being omitted in the response.  That should give us an idea of where the fix is needed, and we can go about getting that put into place to remediate the exception.

I'll follow up here just as soon I have any details or updates to share.

**Comment by james-ingold** [comment]
Anything we can do to move forward on this ASAP? We hit another instance today with a user charged 3 times due to this error. Not the best experience for our customers.

**Comment by james-ingold** [comment]
@PrestonPHX @DPoplin this **production** issue is almost a month old now. Any updates on when a fix is expected to be deployed?

**Comment by james-ingold** [comment]
Yep, I can confirm my patch is working in production. Had to get a bandaid in before Black Friday. Looking forward to a proper fix in the lib. 👍

**Comment by shanemoses-pbtech** [comment]
Hi team, are there any further progress updates or ETAs for an official fix being released?

**Comment by Dani-Kirby** [comment]
Hey @shanemoses-pbtech and @james-ingold very sorry for the delays in getting this fix out. While I can confirm it's not yet released, we are getting very close to a fix and we are hoping to add it to an upcoming release. 

I'll be reaching out again as soon as I can confirm this fix has been released.

**Comment by chrisHushDigital** [comment]
Just to continue this issue. We are experiencing the same error, but in this case no payment is being taken.
Looking at the PayPal API logs, this is only happening with the capture event when a Mastercard Debit card is declined. The response does not contain an id within the "network_transaction_reference" data.

**Comment by maxicus** [comment]
Thanks for the community for that analysis. Confirm the case.
One more case of one more bug in this library.

I’d like to extend my heartfelt congratulations to the developers of that — for snagging the prestigious award for “Most Impressively Bug-Ridden Official API Library” of recent years. Truly, a masterpiece :)
